In [97]:
import glob, os
import re

In [98]:
glob_list = []

#loop through subject folders and glob
for subject in range(25):
    glob_list.append(glob.glob(str(subject) + "\\[0-9a-zA-Z]*.csv"))
    
#function to flatten glob
flatten = lambda l: [item for sublist in l for item in sublist]
glob_list = flatten(glob_list)
glob_list

['0\\0_Left.csv',
 '0\\0_Right.csv',
 '0\\10_Left.csv',
 '0\\10_Right.csv',
 '0\\1_Left.csv',
 '0\\1_Right.csv',
 '0\\2_Left.csv',
 '0\\2_Right.csv',
 '0\\3_Left.csv',
 '0\\3_Right.csv',
 '0\\4_Left.csv',
 '0\\4_Right.csv',
 '0\\5_Left.csv',
 '0\\5_Right.csv',
 '0\\6_Left.csv',
 '0\\6_Right.csv',
 '0\\7_Left.csv',
 '0\\7_Right.csv',
 '0\\8_Left.csv',
 '0\\8_Right.csv',
 '0\\9_Left.csv',
 '0\\9_Right.csv',
 '0\\Big_Left.csv',
 '0\\Big_Right.csv',
 '0\\Blue_Left.csv',
 '0\\Blue_Right.csv',
 '0\\Brush_Left.csv',
 '0\\Brush_Right.csv',
 '0\\Bug_Left.csv',
 '0\\Bug_Right.csv',
 '0\\Candy_Left.csv',
 '0\\Candy_Right.csv',
 '0\\CarDrive_Left.csv',
 '0\\CarDrive_Right.csv',
 '0\\Cat_Left.csv',
 '0\\Cat_Right.csv',
 '0\\Cereal_Left.csv',
 '0\\Cereal_Right.csv',
 '0\\Clothes_Left.csv',
 '0\\Clothes_Right.csv',
 '0\\Coat_Left.csv',
 '0\\Coat_Right.csv',
 '0\\Cold_Left.csv',
 '0\\Cold_Right.csv',
 '0\\Come_Left.csv',
 '0\\Come_Right.csv',
 '0\\Cost_Left.csv',
 '0\\Cost_Right.csv',
 '0\\Cry_Left.cs

In [99]:
#make a list of tuples of hand pairings
lr_pairs = list(zip(*[iter(glob_list)]*2))
for i in range(25):
    lr_pairs.remove((str(i)+'\\Blue_Left.csv', str(i)+'\\Blue_Right.csv'))
lr_pairs

[('0\\0_Left.csv', '0\\0_Right.csv'),
 ('0\\10_Left.csv', '0\\10_Right.csv'),
 ('0\\1_Left.csv', '0\\1_Right.csv'),
 ('0\\2_Left.csv', '0\\2_Right.csv'),
 ('0\\3_Left.csv', '0\\3_Right.csv'),
 ('0\\4_Left.csv', '0\\4_Right.csv'),
 ('0\\5_Left.csv', '0\\5_Right.csv'),
 ('0\\6_Left.csv', '0\\6_Right.csv'),
 ('0\\7_Left.csv', '0\\7_Right.csv'),
 ('0\\8_Left.csv', '0\\8_Right.csv'),
 ('0\\9_Left.csv', '0\\9_Right.csv'),
 ('0\\Big_Left.csv', '0\\Big_Right.csv'),
 ('0\\Brush_Left.csv', '0\\Brush_Right.csv'),
 ('0\\Bug_Left.csv', '0\\Bug_Right.csv'),
 ('0\\Candy_Left.csv', '0\\Candy_Right.csv'),
 ('0\\CarDrive_Left.csv', '0\\CarDrive_Right.csv'),
 ('0\\Cat_Left.csv', '0\\Cat_Right.csv'),
 ('0\\Cereal_Left.csv', '0\\Cereal_Right.csv'),
 ('0\\Clothes_Left.csv', '0\\Clothes_Right.csv'),
 ('0\\Coat_Left.csv', '0\\Coat_Right.csv'),
 ('0\\Cold_Left.csv', '0\\Cold_Right.csv'),
 ('0\\Come_Left.csv', '0\\Come_Right.csv'),
 ('0\\Cost_Left.csv', '0\\Cost_Right.csv'),
 ('0\\Cry_Left.csv', '0\\Cry_Right.c

In [100]:
import pandas as pd

df_list = []

for pair in lr_pairs:
    df_left = pd.read_csv(pair[0], index_col=None).drop(['Unnamed: 0'], axis = 1)
    df_right = pd.read_csv(pair[1], index_col=None).drop(['Unnamed: 0'], axis = 1)
    
    #rename columns
    df_left = df_left.add_prefix('left')
    df_right = df_right.add_prefix('right')
    
    #merge
    df = pd.merge(df_left, df_right, left_on='leftTime', right_on='rightTime').drop('rightTime', axis = 1)

    #covert first column to time object
    df['leftTime'] = pd.to_datetime(df['leftTime'].str[:-3], format = '%H:%M:%S.%f')
    
    #difference between rows
    df = df.diff().iloc[1:]
    df['leftTime'] = df['leftTime'].dt.total_seconds()
    
    #add sign and subject using regex of file name
    subject_sign = re.split(r'\\', re.findall('^[^_]+(?=_)', pair[0])[0])
    df.insert(loc = 0, column = 'Subject', value = subject_sign[0])
    df.insert(loc = 0, column = 'Sign', value = subject_sign[1])
    
#this makes velocity columns

#     for col in df.iloc[:,2:]:
#         df[col + ' velocity'] = df[col]/df['Time']
    
    df_list.append(df)

In [101]:
#all signs (except 'Blue') for 25 subjects
len(df_list)

1500

In [102]:
#example entry
df_list[35]

Sign Subject  leftTime  left thumbProximal_L_X  left thumbProximal_L_Y  \
1    Hungry       0     0.033               -0.003069               -0.005275   
2    Hungry       0     0.026               -0.001764               -0.004115   
3    Hungry       0     0.029               -0.001353               -0.002294   
4    Hungry       0     0.035               -0.002852                0.002370   
5    Hungry       0     0.032               -0.002808                0.001876   
6    Hungry       0     0.034               -0.001709                0.000802   
7    Hungry       0     0.033               -0.001828               -0.000168   
8    Hungry       0     0.035               -0.001109               -0.000421   
9    Hungry       0     0.030               -0.000225               -0.000439   
10   Hungry       0     0.031                0.000299               -0.000374   
11   Hungry       0     0.036                0.000096               -0.001033   
12   Hungry       0     0.034               -0.000293               -0.000483   
13   Hungry       0     0.033               -0.000665               -0.000639   
14   Hungry       0     0.037               -0.001019               -0.000041   
15   Hungry       0     0.029               -0.000916                0.000011   
16   Hungry       0     0.039               -0.001430                0.000147   
17   Hungry       0     0.034               -0.001407                0.000244   
18   Hungry       0     0.033               -0.001667                0.000627   
19   Hungry       0     0.048               -0.001677               -0.000226   
20   Hungry       0     0.032               -0.001612                0.000103   
21   Hungry       0     0.048               -0.000428                0.000179   
22   Hungry       0     0.038                0.000755               -0.000604   
23   Hungry       0     0.038                0.001416               -0.001118   
24   Hungry       0     0.041                0.000754               -0.001511   
25   Hungry       0     0.030               -0.000239               -0.000647   
26   Hungry       0     0.031               -0.000045               -0.001446   
27   Hungry       0     0.035               -0.001324                0.000138   
28   Hungry       0     0.037               -0.000935                0.001203   
29   Hungry       0     0.035               -0.000264                0.000778   
30   Hungry       0     0.043               -0.000112                0.001603   
..      ...     ...       ...                     ...                     ...   
731  Hungry       0     0.034               -0.000394                0.000132   
732  Hungry       0     0.036               -0.000030                0.000046   
733  Hungry       0     0.039                0.000914               -0.000517   
734  Hungry       0     0.035                0.000544               -0.000457   
735  Hungry       0     0.040                0.000738               -0.001113   
736  Hungry       0     0.039               -0.000412               -0.000502   
737  Hungry       0     0.031               -0.000812               -0.000790   
738  Hungry       0     0.042               -0.001317               -0.001572   
739  Hungry       0     0.033               -0.001146               -0.000265   
740  Hungry       0     0.034               -0.000329                0.000419   
741  Hungry       0     0.034               -0.000721                0.000408   
742  Hungry       0     0.035               -0.000134                0.000782   
743  Hungry       0     0.035               -0.000597                0.000696   
744  Hungry       0     0.034               -0.000141                0.001320   
745  Hungry       0     0.033               -0.000042                0.002179   
746  Hungry       0     0.033                0.001453                0.001476   
747  Hungry       0     0.031                0.001221                0.000285   
748  Hungry       0     0.032         

In [103]:
#concatenate list of frames
sign_frame = pd.concat(df_list, axis=0, ignore_index=False)
sign_frame

Sign Subject  leftTime  left thumbProximal_L_X  left thumbProximal_L_Y  \
1         0       0     0.028            3.878000e-04                0.000133   
2         0       0     0.036            4.195000e-04                0.000077   
3         0       0     0.033            2.230000e-04                0.000264   
4         0       0     0.034            1.029000e-04                0.000078   
5         0       0     0.036            5.490000e-05                0.000233   
6         0       0     0.034            5.680000e-05               -0.000107   
7         0       0     0.043           -2.995000e-04                0.000086   
8         0       0     0.035           -3.110000e-04                0.000298   
9         0       0     0.037           -3.372000e-04                0.000358   
10        0       0     0.040           -2.301000e-04                0.000202   
11        0       0     0.037           -1.848000e-04                0.000125   
12        0       0     0.038           -1.174000e-04                0.000162   
13        0       0     0.048            2.397000e-04               -0.000251   
14        0       0     0.042            4.455000e-04               -0.000456   
15        0       0     0.055            6.284000e-04               -0.000355   
16        0       0     0.044            4.862000e-04               -0.000489   
17        0       0     0.042            3.217000e-04               -0.000176   
18        0       0     0.044            1.384000e-04               -0.000163   
19        0       0     0.036            5.170000e-05               -0.000079   
20        0       0     0.039           -1.208000e-04               -0.000120   
21        0       0     0.036           -2.870000e-04                0.000390   
22        0       0     0.032           -3.718000e-04                0.000164   
23        0       0     0.038           -7.760000e-05               -0.000076   
24        0       0     0.037           -5.720000e-05                0.000116   
25        0       0     0.044           -3.500000e-04               -0.000066   
26        0       0     0.040           -9.960000e-05                0.000137   
27        0       0     0.046            1.031000e-04                0.000300   
28        0       0     0.053            1.825000e-04               -0.000166   
29        0       0     0.051            4.372000e-04               -0.000470   
30        0       0     0.050            5.845000e-04               -0.000417   
..      ...     ...       ...                     ...                     ...   
814  Yellow      24     0.037           -1.271500e-04               -0.000127   
815  Yellow      24     0.033            1.908600e-04               -0.000211   
816  Yellow      24     0.035            2.374300e-04               -0.000497   
817  Yellow      24     0.034            1.736200e-04               -0.000289   
818  Yellow      24     0.035            9.460000e-05               -0.000125   
819  Yellow      24     0.035           -1.981800e-04                0.000129   
820  Yellow      24     0.036            1.137000e-05                0.000035   
821  Yellow      24     0.037           -1.965700e-04                0.000281   
822  Yellow      24     0.035            1.093000e-05               -0.000048   
823  Yellow      24     0.038           -2.700000e-07                0.000085   
824  Yellow      24     0.042            2.814400e-04               -0.000251   
825  Yellow      24     0.035            2.618000e-05                0.000024   
826  Yellow      24     0.035           -1.964800e-04                0.000165   
827  Yellow      24     0.035            8.640000e-06                0.000016   
828  Yellow      24     0.036           -1.169900e-04                0.000067   
829  Yellow      24     0.031           -1.973000e-05                0.000098   
830  Yellow      24     0.036           -2.407200e-04                0.000098   
831  Yellow      24     0.035         

In [104]:
agg_df = sign_frame.groupby(['Subject','Sign']).agg(['mean','std'])
agg_df = agg_df.reset_index()
agg_df.head()

Subject Sign  leftTime           left thumbProximal_L_X            \
                    mean       std                   mean       std   
0       0    0  0.043573  0.007938           9.093222e-06  0.000329   
1       0    1  0.041300  0.007824           5.417744e-06  0.000294   
2       0   10  0.065428  0.018792           1.764326e-05  0.000718   
3       0    2  0.041766  0.007072          -3.434540e-07  0.000270   
4       0    3  0.043742  0.008602          -1.805375e-05  0.000445   

  left thumbProximal_L_Y           left thumbProximal_L_Z            ...  \
                    mean       std                   mean       std  ...   
0               0.000013  0.000287              -0.000004  0.000213  ...   
1               0.000025  0.000349              -0.000021  0.000199  ...   
2               0.000009  0.000812              -0.000047  0.000664  ...   
3               0.000022  0.000360              -0.000014  0.000226  ...   
4               0.000025  0.000454              -0.000018  0.000302  ...   

  right armBackLateral_L_Y           right armBackLateral_L_Z            \
                      mean       std                     mean       std   
0            -5.686067e-06  0.004467                 0.000011  0.002841   
1            -2.150715e-05  0.005544                 0.000045  0.004783   
2            -4.001783e-05  0.012821                 0.000206  0.012200   
3            -2.253719e-05  0.006004                 0.000005  0.005082   
4             6.469388e-07  0.004286                 0.000004  0.005211   

  right armBackMedial_L_X           right armBackMedial_L_Y            \
                     mean       std                    mean       std   
0               -0.000033  0.004745               -0.000039  0.004753   
1               -0.000033  0.005855               -0.000014  0.006204   
2               -0.000091  0.012339               -0.000015  0.011673   
3               -0.000006  0.006624               -0.000020  0.006283   
4               -0.000006  0.005767               -0.000001  0.004373   

  right armBackMedial_L_Z            
                     mean       std  
0                0.000025  0.003106  
1                0.000007  0.004511  
2                0.000116  0.007522  
3                0.000006  0.004975  
4                0.000007  0.004265  

[5 rows x 328 columns]

In [105]:
agg_df.shape

(1500, 328)

In [106]:
agg_df = agg_df.dropna(how='any')

In [107]:
# agg_df.isnull().sum()

In [108]:
#Separating features and label
X = agg_df.iloc[:, 2:328]
y = agg_df.iloc[:, 1]

In [109]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [110]:
#Feature scaling

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

**Method 1: Using LDA and Random Forest**

In [111]:
#Performing LDA

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

lda = LDA(n_components=60)
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)

C:\Users\rawin\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


In [112]:
#Train a Random Forest Model

from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=2, random_state=0)

classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

C:\Users\rawin\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [113]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy = ' + str(accuracy_score(y_test, y_pred)))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 4 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Accuracy = 0.19


**Method 2: Using LDA only**

In [114]:
import numpy as np

clf = LDA()
clf.fit(X_train, y_train)
clf.score(X_test,y_test)

0.8