In [1]:
import glob, os
import re

In [2]:
glob_list = []

#loop through subject folders and glob
for subject in range(25):
    glob_list.append(glob.glob(str(subject) + "\\[0-9]*.csv"))
    
#function to flatten glob
flatten = lambda l: [item for sublist in l for item in sublist]
glob_list = flatten(glob_list)
glob_list

['0\\0_Left.csv',
 '0\\0_Right.csv',
 '0\\10_Left.csv',
 '0\\10_Right.csv',
 '0\\1_Left.csv',
 '0\\1_Right.csv',
 '0\\2_Left.csv',
 '0\\2_Right.csv',
 '0\\3_Left.csv',
 '0\\3_Right.csv',
 '0\\4_Left.csv',
 '0\\4_Right.csv',
 '0\\5_Left.csv',
 '0\\5_Right.csv',
 '0\\6_Left.csv',
 '0\\6_Right.csv',
 '0\\7_Left.csv',
 '0\\7_Right.csv',
 '0\\8_Left.csv',
 '0\\8_Right.csv',
 '0\\9_Left.csv',
 '0\\9_Right.csv',
 '1\\0_Left.csv',
 '1\\0_Right.csv',
 '1\\10_Left.csv',
 '1\\10_Right.csv',
 '1\\1_Left.csv',
 '1\\1_Right.csv',
 '1\\2_Left.csv',
 '1\\2_Right.csv',
 '1\\3_Left.csv',
 '1\\3_Right.csv',
 '1\\4_Left.csv',
 '1\\4_Right.csv',
 '1\\5_Left.csv',
 '1\\5_Right.csv',
 '1\\6_Left.csv',
 '1\\6_Right.csv',
 '1\\7_Left.csv',
 '1\\7_Right.csv',
 '1\\8_Left.csv',
 '1\\8_Right.csv',
 '1\\9_Left.csv',
 '1\\9_Right.csv',
 '2\\0_Left.csv',
 '2\\0_Right.csv',
 '2\\10_Left.csv',
 '2\\10_Right.csv',
 '2\\1_Left.csv',
 '2\\1_Right.csv',
 '2\\2_Left.csv',
 '2\\2_Right.csv',
 '2\\3_Left.csv',
 '2\\3_Right.c

In [3]:
#make a list of tuples of hand pairings
lr_pairs = list(zip(*[iter(glob_list)]*2))
lr_pairs

[('0\\0_Left.csv', '0\\0_Right.csv'),
 ('0\\10_Left.csv', '0\\10_Right.csv'),
 ('0\\1_Left.csv', '0\\1_Right.csv'),
 ('0\\2_Left.csv', '0\\2_Right.csv'),
 ('0\\3_Left.csv', '0\\3_Right.csv'),
 ('0\\4_Left.csv', '0\\4_Right.csv'),
 ('0\\5_Left.csv', '0\\5_Right.csv'),
 ('0\\6_Left.csv', '0\\6_Right.csv'),
 ('0\\7_Left.csv', '0\\7_Right.csv'),
 ('0\\8_Left.csv', '0\\8_Right.csv'),
 ('0\\9_Left.csv', '0\\9_Right.csv'),
 ('1\\0_Left.csv', '1\\0_Right.csv'),
 ('1\\10_Left.csv', '1\\10_Right.csv'),
 ('1\\1_Left.csv', '1\\1_Right.csv'),
 ('1\\2_Left.csv', '1\\2_Right.csv'),
 ('1\\3_Left.csv', '1\\3_Right.csv'),
 ('1\\4_Left.csv', '1\\4_Right.csv'),
 ('1\\5_Left.csv', '1\\5_Right.csv'),
 ('1\\6_Left.csv', '1\\6_Right.csv'),
 ('1\\7_Left.csv', '1\\7_Right.csv'),
 ('1\\8_Left.csv', '1\\8_Right.csv'),
 ('1\\9_Left.csv', '1\\9_Right.csv'),
 ('2\\0_Left.csv', '2\\0_Right.csv'),
 ('2\\10_Left.csv', '2\\10_Right.csv'),
 ('2\\1_Left.csv', '2\\1_Right.csv'),
 ('2\\2_Left.csv', '2\\2_Right.csv'),
 ('2\\

In [4]:
import pandas as pd

df_list = []

for pair in lr_pairs:
    df_left = pd.read_csv(pair[0], index_col=None).drop(['Unnamed: 0'], axis = 1)
    df_right = pd.read_csv(pair[1], index_col=None).drop(['Unnamed: 0'], axis = 1)
    
    #rename columns
    df_left = df_left.add_prefix('left')
    df_right = df_right.add_prefix('right')
    
    #merge
    df = pd.merge(df_left, df_right, left_on='leftTime', right_on='rightTime').drop('rightTime', axis = 1)

    #covert fist column to time object
    df['leftTime'] = pd.to_datetime(df['leftTime'].str[:-3], format = '%H:%M:%S.%f')
    
    #difference between rows
    df = df.diff().iloc[1:]
    df['leftTime'] = df['leftTime'].dt.total_seconds()
    
    #add sign and subject using regex of file name
    subject_sign = re.split(r'\\', re.findall('^[^_]+(?=_)', pair[0])[0])
    df.insert(loc = 0, column = 'Subject', value = subject_sign[0])
    df.insert(loc = 0, column = 'Sign', value = subject_sign[1])
    
#this makes velocity columns

#     for col in df.iloc[:,2:]:
#         df[col + ' velocity'] = df[col]/df['Time']
    
    df_list.append(df)

In [5]:
#numbers 0-10 for 25 subjects
len(df_list)

275

In [6]:
#example entry
df_list[35]

Sign Subject  leftTime  left thumbProximal_L_X  left thumbProximal_L_Y  \
1      1       3     0.024               -0.000577            1.844800e-04   
2      1       3     0.020               -0.000593            4.397900e-04   
3      1       3     0.029               -0.000376            2.671000e-05   
4      1       3     0.032               -0.001070            5.973500e-04   
5      1       3     0.028               -0.000710            4.489200e-04   
6      1       3     0.028               -0.000179            1.419500e-04   
7      1       3     0.030               -0.000151            9.140000e-05   
8      1       3     0.030                0.000102           -2.486000e-05   
9      1       3     0.028               -0.000021           -2.802900e-04   
10     1       3     0.030                0.000150           -3.657600e-04   
11     1       3     0.029                0.000211           -1.636200e-04   
12     1       3     0.031                0.000381            3.000000e-07   
13     1       3     0.030                0.000086            1.637400e-04   
14     1       3     0.042               -0.000005            4.181500e-04   
15     1       3     0.042               -0.000065            2.791000e-04   
16     1       3     0.038               -0.000043            1.044900e-04   
17     1       3     0.034                0.000141            1.329000e-05   
18     1       3     0.040                0.000050            1.498800e-04   
19     1       3     0.035               -0.000140            8.744000e-05   
20     1       3     0.029               -0.000289            1.470700e-04   
21     1       3     0.033               -0.000154            3.290000e-05   
22     1       3     0.028               -0.000140            8.590000e-06   
23     1       3     0.030               -0.000689            1.280900e-04   
24     1       3     0.028               -0.000669            7.528000e-05   
25     1       3     0.029               -0.000861           -1.865400e-04   
26     1       3     0.031               -0.000840           -1.058000e-05   
27     1       3     0.029               -0.001167            6.422100e-04   
28     1       3     0.031                0.000005            1.169360e-03   
29     1       3     0.029               -0.000570            6.823200e-04   
30     1       3     0.030               -0.000519            2.492100e-04   
..   ...     ...       ...                     ...                     ...   
918    1       3     0.029                0.000410           -2.061700e-04   
919    1       3     0.030                0.000509           -2.362800e-04   
920    1       3     0.029                0.000506           -3.173000e-04   
921    1       3     0.031                0.000503           -3.981300e-04   
922    1       3     0.031                0.000424           -3.788800e-04   
923    1       3     0.032                0.000200           -3.286300e-04   
924    1       3     0.033               -0.000019            2.374700e-04   
925    1       3     0.034               -0.000315            2.715500e-04   
926    1       3     0.029               -0.000337           -3.960000e-05   
927    1       3     0.033               -0.000520           -2.441100e-04   
928    1       3     0.030               -0.000655            4.192900e-04   
929    1       3     0.033               -0.000466            1.467100e-04   
930    1       3     0.034               -0.000111           -5.358000e-05   
931    1       3     0.033               -0.000255            1.166700e-04   
932    1       3     0.034               -0.000030            5.627000e-05   
933    1       3     0.032                0.000145           -1.061000e-04   
934    1       3     0.033                0.000410            2.780000e-06   
935    1       3     0.034                0.000343            4.133000e-05   
936    1       3     0.031                0.000280           -4.956000e-05   
937    1       3     0.029

In [7]:
#concatenate list of frames
sign_frame = pd.concat(df_list, axis=0, ignore_index=False)
sign_frame

Sign Subject  leftTime  left thumbProximal_L_X  left thumbProximal_L_Y  \
1      0       0     0.028                0.000388                0.000133   
2      0       0     0.036                0.000420                0.000077   
3      0       0     0.033                0.000223                0.000264   
4      0       0     0.034                0.000103                0.000078   
5      0       0     0.036                0.000055                0.000233   
6      0       0     0.034                0.000057               -0.000107   
7      0       0     0.043               -0.000299                0.000086   
8      0       0     0.035               -0.000311                0.000298   
9      0       0     0.037               -0.000337                0.000358   
10     0       0     0.040               -0.000230                0.000202   
11     0       0     0.037               -0.000185                0.000125   
12     0       0     0.038               -0.000117                0.000162   
13     0       0     0.048                0.000240               -0.000251   
14     0       0     0.042                0.000446               -0.000456   
15     0       0     0.055                0.000628               -0.000355   
16     0       0     0.044                0.000486               -0.000489   
17     0       0     0.042                0.000322               -0.000176   
18     0       0     0.044                0.000138               -0.000163   
19     0       0     0.036                0.000052               -0.000079   
20     0       0     0.039               -0.000121               -0.000120   
21     0       0     0.036               -0.000287                0.000390   
22     0       0     0.032               -0.000372                0.000164   
23     0       0     0.038               -0.000078               -0.000076   
24     0       0     0.037               -0.000057                0.000116   
25     0       0     0.044               -0.000350               -0.000066   
26     0       0     0.040               -0.000100                0.000137   
27     0       0     0.046                0.000103                0.000300   
28     0       0     0.053                0.000182               -0.000166   
29     0       0     0.051                0.000437               -0.000470   
30     0       0     0.050                0.000585               -0.000417   
..   ...     ...       ...                     ...                     ...   
762    9      24     0.035                0.000277               -0.000082   
763    9      24     0.057                0.000388               -0.000276   
764    9      24     0.043                0.000250               -0.000181   
765    9      24     0.039                0.000201               -0.000032   
766    9      24     0.039                0.000206               -0.000268   
767    9      24     0.042                0.000156               -0.000270   
768    9      24     0.036                0.000053               -0.000337   
769    9      24     0.037               -0.000035               -0.000356   
770    9      24     0.037               -0.000064               -0.000224   
771    9      24     0.037                0.000061                0.000022   
772    9      24     0.037                0.000077               -0.000111   
773    9      24     0.038               -0.000035               -0.000160   
774    9      24     0.035               -0.000146                0.000088   
775    9      24     0.037               -0.000280                0.000410   
776    9      24     0.037               -0.000329                0.000451   
777    9      24     0.044                0.000014                0.000151   
778    9      24     0.041                0.000258               -0.000108   
779    9      24     0.039                0.000071                0.000081   
780    9      24     0.045               -0.000039                0.000039   
781    9      24     0.038

In [8]:
#this is the still hand for signing numbers
sign_frame.groupby('Sign')['left thumbProximal_L_X'].agg('mean')

Sign
0     0.000008
1     0.000009
10    0.000008
2     0.000005
3     0.000006
4     0.000006
5     0.000014
6     0.000005
7     0.000006
8     0.000010
9     0.000008
Name: left thumbProximal_L_X, dtype: float64

In [22]:
agg_df = sign_frame.groupby(['Subject','Sign']).agg(['mean','std'])
agg_df = agg_df.reset_index()
agg_df.head()

Subject Sign  leftTime           left thumbProximal_L_X            \
                    mean       std                   mean       std   
0       0    0  0.043573  0.007938           9.093222e-06  0.000329   
1       0    1  0.041300  0.007824           5.417744e-06  0.000294   
2       0   10  0.065428  0.018792           1.764326e-05  0.000718   
3       0    2  0.041766  0.007072          -3.434540e-07  0.000270   
4       0    3  0.043742  0.008602          -1.805375e-05  0.000445   

  left thumbProximal_L_Y           left thumbProximal_L_Z            ...  \
                    mean       std                   mean       std  ...   
0               0.000013  0.000287              -0.000004  0.000213  ...   
1               0.000025  0.000349              -0.000021  0.000199  ...   
2               0.000009  0.000812              -0.000047  0.000664  ...   
3               0.000022  0.000360              -0.000014  0.000226  ...   
4               0.000025  0.000454              -0.000018  0.000302  ...   

  right armBackLateral_L_Y           right armBackLateral_L_Z            \
                      mean       std                     mean       std   
0            -5.686067e-06  0.004467                 0.000011  0.002841   
1            -2.150715e-05  0.005544                 0.000045  0.004783   
2            -4.001783e-05  0.012821                 0.000206  0.012200   
3            -2.253719e-05  0.006004                 0.000005  0.005082   
4             6.469388e-07  0.004286                 0.000004  0.005211   

  right armBackMedial_L_X           right armBackMedial_L_Y            \
                     mean       std                    mean       std   
0               -0.000033  0.004745               -0.000039  0.004753   
1               -0.000033  0.005855               -0.000014  0.006204   
2               -0.000091  0.012339               -0.000015  0.011673   
3               -0.000006  0.006624               -0.000020  0.006283   
4               -0.000006  0.005767               -0.000001  0.004373   

  right armBackMedial_L_Z            
                     mean       std  
0                0.000025  0.003106  
1                0.000007  0.004511  
2                0.000116  0.007522  
3                0.000006  0.004975  
4                0.000007  0.004265  

[5 rows x 328 columns]

In [23]:
agg_df.shape

(275, 328)

In [24]:
agg_df = agg_df.dropna(how='any')

In [25]:
# agg_df.isnull().sum()

In [34]:
#Separating features and label
X = agg_df.iloc[:, 2:328]
y = agg_df.iloc[:, 1]

In [35]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [36]:
#Feature scaling

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

**Method 1: Using LDA and Random Forest**

In [37]:
#Performing LDA

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

lda = LDA(n_components=60)
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)

C:\Users\rawin\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:466: ChangedBehaviorWarning: n_components cannot be larger than min(n_features, n_classes - 1). Using min(n_features, n_classes - 1) = min(326, 11 - 1) = 10 components.
  ChangedBehaviorWarning)
C:\Users\rawin\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:472: FutureWarning: In version 0.23, setting n_components > min(n_features, n_classes - 1) will raise a ValueError. You should set n_components to None (default), or a value smaller or equal to min(n_features, n_classes - 1).
  warnings.warn(future_msg, FutureWarning)
C:\Users\rawin\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


In [38]:
#Train a Random Forest Model

from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=2, random_state=0)

classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

C:\Users\rawin\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [39]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy = ' + str(accuracy_score(y_test, y_pred)))

[[0 2 0 0 1 1 1 0 0 0 0]
 [0 1 0 0 0 4 0 0 0 0 0]
 [0 0 2 0 0 1 0 0 0 0 0]
 [0 0 0 1 0 1 1 0 1 0 0]
 [0 0 0 0 0 4 0 0 1 0 2]
 [0 0 0 0 0 6 0 0 0 0 0]
 [0 0 0 0 0 2 2 0 0 0 0]
 [0 0 0 0 0 1 0 1 0 0 4]
 [0 0 0 0 0 0 2 0 2 0 1]
 [0 0 0 0 0 2 4 0 0 0 1]
 [0 0 0 0 0 1 1 0 0 0 1]]
Accuracy = 0.2909090909090909


**Method 2: Using LDA only**

In [40]:
import numpy as np

clf = LDA()
clf.fit(X_train, y_train)
clf.score(X_test,y_test)

0.6727272727272727